name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_gbkCwnpsKnkbuQJ9YLu14AkQ
          VERCEL_PROJECT_ID: prj_CBtScQ9fQXH6JL3EBgQO5jgEbo2T
